import sys

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1022, 879)
        MainWindow.setMinimumSize(QtCore.QSize(60, 120))
        MainWindow.setBaseSize(QtCore.QSize(5, 5))
        MainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        MainWindow.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(50, 30, 321, 361))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.formLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalSlider = QtWidgets.QSlider(self.formLayoutWidget)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout.addWidget(self.horizontalSlider, 12, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox.setStyleSheet("color:rgb(0, 15, 0);\n"
                                    "color-back-ground:rgb(126, 255, 245);\n"
                                    "")
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 10, 0, 1, 1)
        self.spinBox_Size = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_Size.setStyleSheet("color:rgb(0, 0, 0);")
        self.spinBox_Size.setMinimum(100)
        self.spinBox_Size.setMaximum(50000)
        self.spinBox_Size.setProperty("value", 100)
        self.spinBox_Size.setObjectName("spinBox_Size")
        self.gridLayout.addWidget(self.spinBox_Size, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.spinBox_limitA = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_limitA.setStyleSheet("color:rgb(0, 0, 0);")
        self.spinBox_limitA.setMinimum(0)
        self.spinBox_limitA.setMaximum(50000)
        self.spinBox_limitA.setProperty("value", 0)
        self.spinBox_limitA.setObjectName("spinBox_limitA")
        self.gridLayout.addWidget(self.spinBox_limitA, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.spinBox_limitB = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_limitB.setStyleSheet("color:rgb(0, 0, 0);")
        self.spinBox_limitB.setMinimum(0)
        self.spinBox_limitB.setMaximum(50000)
        self.spinBox_limitB.setProperty("value", 0)
        self.spinBox_limitB.setObjectName("spinBox_limitB")
        self.gridLayout.addWidget(self.spinBox_limitB, 6, 0, 1, 1)
        self.labelSize = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelSize.setFont(font)
        self.labelSize.setStyleSheet("color:rgb(0,0,0);")
        self.labelSize.setObjectName("labelSize")
        self.gridLayout.addWidget(self.labelSize, 0, 1, 1, 1)
        self.labelBorderA = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelBorderA.setFont(font)
        self.labelBorderA.setStyleSheet("color:rgb(0,0,0);")
        self.labelBorderA.setObjectName("labelBorderA")
        self.gridLayout.addWidget(self.labelBorderA, 3, 1, 1, 1)
        self.labelBorderB = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelBorderB.setFont(font)
        self.labelBorderB.setStyleSheet("color:rgb(0,0,0);")
        self.labelBorderB.setObjectName("labelBorderB")
        self.gridLayout.addWidget(self.labelBorderB, 6, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 8, 0, 1, 1)
        self.AlgoLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.AlgoLabel.setFont(font)
        self.AlgoLabel.setStyleSheet("color:rgb(0,0,0);")
        self.AlgoLabel.setObjectName("AlgoLabel")
        self.gridLayout.addWidget(self.AlgoLabel, 10, 1, 1, 1)
        self.SpeedBtn = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.SpeedBtn.setFont(font)
        self.SpeedBtn.setStyleSheet("color:rgb(0,0,0);")
        self.SpeedBtn.setObjectName("SpeedBtn")
        self.gridLayout.addWidget(self.SpeedBtn, 12, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 11, 0, 1, 1)
        self.PlotFrame = QtWidgets.QFrame(self.centralwidget)
        self.PlotFrame.setGeometry(QtCore.QRect(400, 10, 571, 451))
        self.PlotFrame.setObjectName("PlotFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.PlotFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.PlotFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 547, 427))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(770, 670, 191, 107))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        spacerItem4 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem4)
        self.nameField = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.nameField.setObjectName("nameField")
        self.verticalLayout_2.addWidget(self.nameField)
        spacerItem5 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem5)
        self.StartBtn = QtWidgets.QPushButton(self.centralwidget)
        self.StartBtn.setGeometry(QtCore.QRect(120, 420, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.StartBtn.setFont(font)
        self.StartBtn.setMouseTracking(False)
        self.StartBtn.setStyleSheet("QPushButton{\n"
                                    "background-color:rgb(105, 133, 255);\n"
                                    "border-style:outset;\n"
                                    "border-with:2px;\n"
                                    "border-radius:8px;\n"
                                    "}\n"
                                    "QPushButton:pressed{\n"
                                    " background-color:rgb(85, 120, 250);\n"
                                    "}\n"
                                    "")
        self.StartBtn.setObjectName("StartBtn")
        self.SaveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.SaveBtn.setEnabled(True)
        self.SaveBtn.setGeometry(QtCore.QRect(770, 790, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SaveBtn.setFont(font)
        self.SaveBtn.setMouseTracking(False)
        self.SaveBtn.setStyleSheet("QPushButton{\n"
                                   "background-color:rgb(105, 133, 255);\n"
                                   "border-style:outset;\n"
                                   "border-with:2px;\n"
                                   "border-radius:8px;\n"
                                   "}\n"
                                   "QPushButton:pressed{\n"
                                   " background-color:rgb(85, 120, 250);\n"
                                   "}\n"
                                   "")
        self.SaveBtn.setObjectName("SaveBtn")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(40, 490, 701, 350))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.formLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 0, 1, 1, 1)
        self.scrollAreaS = QtWidgets.QScrollArea(self.formLayoutWidget_2)
        self.scrollAreaS.setMinimumSize(QtCore.QSize(320, 320))
        self.scrollAreaS.setWidgetResizable(True)
        self.scrollAreaS.setObjectName("scrollAreaS")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 331, 318))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.scrollAreaS.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_2.addWidget(self.scrollAreaS, 1, 0, 1, 1)
        self.UnordArrLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.UnordArrLabel.setFont(font)
        self.UnordArrLabel.setObjectName("UnordArrLabel")
        self.gridLayout_2.addWidget(self.UnordArrLabel, 0, 2, 1, 1)
        self.SortArrayLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SortArrayLabel.setFont(font)
        self.SortArrayLabel.setObjectName("SortArrayLabel")
        self.gridLayout_2.addWidget(self.SortArrayLabel, 0, 0, 1, 1)
        self.scrollAreaUS = QtWidgets.QScrollArea(self.formLayoutWidget_2)
        self.scrollAreaUS.setMinimumSize(QtCore.QSize(320, 320))
        self.scrollAreaUS.setWidgetResizable(True)
        self.scrollAreaUS.setObjectName("scrollAreaUS")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 330, 318))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollAreaUS.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.addWidget(self.scrollAreaUS, 1, 2, 1, 1)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(770, 490, 191, 161))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.comp = QtWidgets.QLCDNumber(self.verticalLayoutWidget_2)
        self.comp.setObjectName("comp")
        self.verticalLayout_3.addWidget(self.comp)
        spacerItem7 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem7)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.swap = QtWidgets.QLCDNumber(self.verticalLayoutWidget_2)
        self.swap.setObjectName("swap")
        self.verticalLayout_3.addWidget(self.swap)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelSize.setText(_translate("MainWindow", "Size of array"))
        self.labelBorderA.setText(_translate("MainWindow", "First element"))
        self.labelBorderB.setText(_translate("MainWindow", "Last element"))
        self.AlgoLabel.setText(_translate("MainWindow", "Algorithm"))
        self.SpeedBtn.setText(_translate("MainWindow", "Speed"))
        self.label.setText(_translate("MainWindow", "Enter name of file to\n"
                                                    "save sorted array"))
        self.StartBtn.setText(_translate("MainWindow", "Sort"))
        self.SaveBtn.setText(_translate("MainWindow", "Save"))
        self.UnordArrLabel.setText(_translate("MainWindow", "Unsorted array"))
        self.SortArrayLabel.setText(_translate("MainWindow", "Sorted array"))
        self.label_2.setText(_translate("MainWindow", "Number of\n"
                                                      "comparisons:"))
        self.label_3.setText(_translate("MainWindow", "swaps:"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())




# import sys
# import random
# import matplotlib
#
# matplotlib.use("Qt5Agg")
# from PyQt5 import QtCore
# from PyQt5.QtWidgets import QApplication, QMainWindow, QMenu, QVBoxLayout, QSizePolicy, QMessageBox, QWidget
# from numpy import arange, sin, pi
# from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
# from matplotlib.figure import Figure
#
#
# class MyMplCanvas(FigureCanvas):
#     """Ultimately, this is a QWidget (as well as a FigureCanvasAgg, etc.)."""
#
#     def __init__(self, parent=None, width=5, height=4, dpi=100):
#         fig = Figure(figsize=(width, height), dpi=dpi)
#         self.axes = fig.add_subplot(111)
#         # We want the axes cleared every time plot() is called
#         self.axes.clear()
#
#         self.compute_initial_figure()
#
#         #
#         FigureCanvas.__init__(self, fig)
#         self.setParent(parent)
#
#         FigureCanvas.setSizePolicy(self, QSizePolicy.Expanding, QSizePolicy.Expanding)
#         FigureCanvas.updateGeometry(self)
#
#     def compute_initial_figure(self):
#         pass
#
#
# class MyStaticMplCanvas(MyMplCanvas):
#     """Simple canvas with a sine plot."""
#
#     def compute_initial_figure(self):
#         t = arange(0.0, 3.0, 0.01)
#         s = sin(2 * pi * t)
#         self.axes.plot(t, s)
#
#
# class MyDynamicMplCanvas(MyMplCanvas):
#     """A canvas that updates itself every second with a new plot."""
#
#     def __init__(self, *args, **kwargs):
#         MyMplCanvas.__init__(self, *args, **kwargs)
#         timer = QtCore.QTimer(self)
#         timer.timeout.connect(self.update_figure)
#         timer.start(1000)
#
#     def compute_initial_figure(self):
#         self.axes.plot([0, 1, 2, 3], [1, 2, 0, 4], 'r')
#
#     def update_figure(self):
#         # Build a list of 4 random integers between 0 and 10 (both inclusive)
#         l = [random.randint(0, 10) for i in range(4)]
#
#         self.axes.plot([0, 1, 2, 3], l, 'r')
#         self.draw()
#
#
# class ApplicationWindow(QMainWindow):
#     def __init__(self):
#         QMainWindow.__init__(self)
#         self.setAttribute(QtCore.Qt.WA_DeleteOnClose)
#         self.setWindowTitle("application main window")
#
#         self.file_menu = QMenu('&File', self)
#         self.file_menu.addAction('&Quit', self.fileQuit,
#                                  QtCore.Qt.CTRL + QtCore.Qt.Key_Q)
#         self.menuBar().addMenu(self.file_menu)
#
#         self.help_menu = QMenu('&Help', self)
#         self.menuBar().addSeparator()
#         self.menuBar().addMenu(self.help_menu)
#
#         self.help_menu.addAction('&About', self.about)
#
#         self.main_widget = QWidget(self)
#
#         l = QVBoxLayout(self.main_widget)
#         sc = MyStaticMplCanvas(self.main_widget, width=5, height=4, dpi=100)
#         dc = MyDynamicMplCanvas(self.main_widget, width=5, height=4, dpi=100)
#         l.addWidget(sc)
#         l.addWidget(dc)
#
#         self.main_widget.setFocus()
#         self.setCentralWidget(self.main_widget)
#
#         self.statusBar().showMessage("All hail matplotlib!", 2000)
#
#     def fileQuit(self):
#         self.close()
#
#     def closeEvent(self, ce):
#         self.fileQuit()
#
#     def about(self):
#         QMessageBox.about(self, "About",
#                           """embedding_in_qt5.py example
#   Copyright 2015 BoxControL
#   This program is a simple example of a Qt5 application embedding matplotlib
#   canvases. It is base on example from matplolib documentation, and initially was
#   developed from Florent Rougon and Darren Dale.
#   http://matplotlib.org/examples/user_interfaces/embedding_in_qt4.html
#   It may be used and modified with no restriction; raw copies as well as
#   modified versions may be distributed without limitation."""
#                           )
#
#
# if __name__ == '__main__':
#     app = QApplication(sys.argv)
#
#     aw = ApplicationWindow()
#     aw.setWindowTitle("PyQt5 Matplot Example")
#     aw.show()
#     # sys.exit(qApp.exec_())
#     app.exec_()
